@startuml Class_CN
hide empty members

用户 <-left-> 管理员
管理员 "1" --- "1" 账户管理器
管理员 <-> 配置表
账户管理器 "1" --- "n" 账户
用户 "1" --- "1" 账户
用户 "1" --- "n" 好友
用户 "1" --- "n" 好友分组
用户 "1" --- "n" 聊天信息
用户 -up-> 登录事件
用户 -up-> 注册事件
用户 -up-> 好友事件
用户 -up-> 聊天事件
用户 <-left-> 外部聊天系统
好友 "n" -right- "1" 好友分组
事件 <|-- 登录事件 
事件 <|-- 注册事件 
事件 <|-- 好友事件
事件 <|-- 聊天事件 

class 用户 {
  - 在线状态
  - 账户信息
  - 好友列表
  - 好友分组
  - 聊天信息列表
  + 注册()
  + 登录()
  + 更新账户信息()
  + 添加好友()
  + 删除好友()
  + 导入好友()
  + 创建好友分组()
  + 删除好友分组()
  + 移动好友()
  + 发送聊天信息()
  + 接受聊天信息()
}

class 管理员 {
  - 密码
  - 账户管理器
  + 审核注册()
  + 设置离线消息保存时限()
}

class 配置表 {
  - 审核规则
  - 保存时限
  + 修改配置
}

class 外部聊天系统 {
  + 生成用户列表()
}

class 账户管理器 {
  - 账户列表
  + 创建账户()
  + 删除账户()
  + 查询账户()
  + 更新账户信息()
}

class 账户 {
  - 邮箱
  - 用户名
  - 密码
}

class 好友分组 {
  - 分组名
  - 好友列表
  + 移入()
  + 移出()
}

class 好友 {
  - 用户名
  - 所属分组
}

class 聊天信息 {
  - 发送者
  - 接受者
  - 时间
  - 聊天内容
}

class 事件 {
  - 类型
  - 时间
  - 具体数据
}

class 好友事件 {
  - 好友信息 @override 具体数据
}

class 聊天事件 {
  - 聊天信息 @override 具体数据
}

class 注册事件 {
  - 账户信息 @override 具体数据
}

class 登录事件 {
  - 账户信息 @override 具体数据
}
@enduml
