@startuml UISalt
salt
{^"添加好友面板"
  "请输入想要添加为好友的用户名 ..." | [查询用户]
  搜索结果（符合字符串的用户 ID） | [添加好友]
  搜索结果（符合字符串的用户 ID） | [添加好友]
  ... | [添加好友]
  ... | [添加好友]
  ... | [添加好友]
  搜索结果（符合字符串的用户 ID） | [添加好友]
  搜索结果（符合字符串的用户 ID） | [添加好友]
  [返回]
}
@enduml

@startuml UIClass
package UI <<Folder>> {
  添加好友面板 "1" o-- "1" 搜索框
  添加好友面板 "1" o-- "n" 文本框
  添加好友面板 "1" o-- "n" 按钮
  添加好友面板 --> 搜索框
  添加好友面板 --> 文本框
  添加好友面板 --> 按钮
  文本框 "1" -right- "1" 按钮
  按钮 "1" -right- "1" 搜索框
  class 添加好友面板 << (@, #FF7700) >> {
    - 句柄
    - 标题
    - 大小
    - 位置
    - 颜色
    - 状态
    + @启动()
    + 移动()
    + 缩放()
  }

  class 搜索框 {
    - 搜索字符串
    - 位置
    - 大小
    + 激活()
    + 键入()
  }

  class 文本框 {
    - 文本内容
    - 字体
    - 字号
    - 颜色
    - 位置
    + 移动()
  }

  class 按钮 {
    - 标题
    - 位置
    - 颜色
    - 大小
    + 激活()
    + 选中()
  }
}

按钮 --> 账户管理器
按钮 --> 用户

class 账户管理器 << (@, #FF7700) >> {
  - 账户列表
  + @查询账户()
}

class 用户 << (@, #FF7700) >> {
  - 好友列表
  + @添加好友()
}
@enduml
