language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules
  - $HOME/.npm

script:
  - npm install
  - cd ./css/material-menu-button && npm install && npm run build && rm -fr src && mv ./build/* . && cd ../../
  - cd ./ife/2018/basic/mis && npm install && npm run build && rm -fr src && mv ./build/* . && cd ../../../../
  - cd ./ife/2018/basic/oop && npm install && npm run build && rm -fr src && mv ./build/* . && cd ../../../../
  - npm run build

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  name: $GIT_NAME
  email: $GIT_EMAIL
  on:
    branch: master
