language: node_js

node_js:
  - 11

cache:
  directories:
  - node_modules
  - $HOME/.npm

script:
  - npm install
  - bash ci.sh
  - npm run build

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
