nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@apollo/client@*":
    peerDependenciesMeta:
      graphql:
        optional: true
  apollo-link-http-common@*:
    peerDependenciesMeta:
      graphql:
        optional: true
  apollo-link@*:
    peerDependenciesMeta:
      graphql:
        optional: true
  eslint-utils@*:
    peerDependenciesMeta:
      eslint:
        optional: true
  fork-ts-checker-webpack-plugin@*:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  postcss-scss@*:
    peerDependenciesMeta:
      postcss:
        optional: true
  ts-node@*:
    peerDependenciesMeta:
      typescript:
        optional: true

yarnPath: .yarn/releases/yarn-3.1.0.cjs
