nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@phenomnomnominal/tsquery@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  eslint-utils@*:
    peerDependenciesMeta:
      eslint:
        optional: true
  fork-ts-checker-webpack-plugin@*:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  postcss-scss@*:
    peerDependenciesMeta:
      postcss:
        optional: true
  react-frame-component@*:
    peerDependenciesMeta:
      prop-types:
        optional: true
      react-dom:
        optional: true

yarnPath: .yarn/releases/yarn-3.5.0.cjs
