yarnPath: '.yarn/releases/yarn-berry.cjs'
nodeLinker: 'node-modules'
npmPublishAccess: 'public'
npmPublishRegistry: 'https://registry.npmjs.org'
npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  "@apollo/client@*":
    peerDependenciesMeta:
      "graphql":
        optional: true
  "apollo-link@*":
    peerDependenciesMeta:
      "graphql":
        optional: true
  "apollo-link-http-common@*":
    peerDependenciesMeta:
      "graphql":
        optional: true
  "fork-ts-checker-webpack-plugin@*":
    peerDependenciesMeta:
      "typescript":
        optional: true
      "webpack":
        optional: true
  "ts-node@*":
    peerDependenciesMeta:
      "typescript":
        optional: true
