name: Continuous Integration

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        node-version:
        - 11
        architecture:
        - x64
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 1

    - name: Setup
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.architecture }}
        registry-url: https://registry.npmjs.org/
        cache: 'npm'

    - name: Installation and Building Work
      run: |
          npm ci
          bash ci.sh
          npm run build
    # - run: npm run build --if-present
    # - run: npm test

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
    # - run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{secrets.npm_token}}
