name: Pull Request Check

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Node ${{ matrix.node-version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        node-version:
        - 11
        architecture:
        - x64
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 1
    - name: Setup Node environment
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.architecture }}
        registry-url: https://registry.npmjs.org/
        cache: 'npm'
    - name: Installation
      run: npm ci
    - name: Building work
      run: |
          bash ci.sh
          npm run lint --if-present
          npm run build --if-present
          npm run test --if-present
    - name: List production artifacts
      run: ls
      working-directory: build
